title: Adolfo Alsina
defaultContentLanguage: 'en'
theme: eternity
baseURL: https://al-sina.github.io

params:
  dontShowLogo: true # please, do not do this :)
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 2
  socials:
    - icon: 'fa-solid fa-envelope fa-lg'
      url: 'mailto:aalsina@igc.gulbenkian.pt'
      landing: true
    - icon: 'fa-solid fa-graduation-cap fa-lg'
      url: 'https://scholar.google.com/citations?user=LBO33WsAAAAJ&hl=en'
      landing: true
    - icon: 'fab fa-orcid fa-lg'
      url: 'https://orcid.org/0000-0003-2173-0777'

  disableWelcomePageBackground: true
  homepage: /about
  bypassWelcomePage: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  
menu:
  main:
     - name: Research
       url: /research
       weight: 1
     - name: CV
       url: /cv
       weight: 2
     - name: Publications
       url: /papers
       weight: 3
      
